server:
  port: 8900
  
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/issueBook/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/returnBook/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/addStudent/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/getStudent/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/deleteStudent/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/updateStudent/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/addBook/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/getBook/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/updateBook/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/deleteBook/**
  application:
    name: Gateway
          